# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'ChessAggregator' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'SwiftSoup'
  
end
